#! /bin/bash

#getopts
OPTIND=1

Useplugs=0
RemoveOld=0


while getopts ":brph?" opt; do
    case "$opt" in
        h|\?)
            cat etc/install_help.txt
            exit 0
            ;;
        p)
            echo 'use plugins'
            Useplugs=1
            ;;
        b)
            etc/backup
            ;;
    esac
done

#remove old config files
if (( $RemoveOld == 1 ))
then
    rm -rf ~/.vim ~/.vimrc ~/.ideavimrc ~/.tmux.conf
fi

#install tmux config
cp tmux/tmux.conf ~/.tmux.conf

#build vim files for repo
cd vim
make idea
make vimrc
if (( $Useplugs == 1 ))
then
    make plugins
    mv vimrc_plugins ..
fi
mv vimrc ideavimrc ..
make clean
cd ..

#install vim files
cp ideavimrc ~/.ideavimrc
if (( $Useplugs == 1 ))
then
    cp vimrc_plugins ~/.vimrc
else
    cp vimrc ~/.vimrc
fi
