#! /bin/bash
#backups vim and tmux files into utils_backup.tar.gz

files=""

if [ -e ~/.vimrc ] 
then 
    files="$files .vimrc"
fi

if [ -e ~/.ideavimrc ] 
then 
    files="$files .ideavimrc"
fi

if [ -e ~/.tmux.conf ] 
then 
    files="$files .tmux.conf"
fi

if [ -d ~/.vim ] 
then
    files="$files .vim"
fi

if [ files != "" ] 
then
    cd ~
    tar -zcvf ~/utils_backup.tar.gz $files
fi


